version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: pass
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    ports:
      - "3306:3306"
    networks:
      - app-network

  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    networks:
      - app-network

  gate-simulator:
    build:
      context: ./gate-simulator
    container_name: gate-simulator
    ports:
      - "9999:9999"
    volumes:
      - ./gate-simulator/data.json:/app/data.json
    networks:
      - app-network

networks:
  app-network:
    driver: bridge